language: python
python:
  - "3.9"

services:
  - docker

before_install:
  - echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin

before_script: pip install docker-compose

script:
  - docker-compose run poco_grabber_api sh -c "python manage.py wait_for_db && python manage.py add_system_user"
  - docker-compose run poco_grabber_api sh -c "python manage.py test && flake8 && python manage.py test poco_common && flake8"