version: "3"

services:
  poco_grabber_api:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./poco_grabber_api:/poco_grabber_api
      - ./poco_common:/py-packages/poco_common
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=supersecretpassword
    depends_on:
      - db
      - redis

  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpassword

  redis:
    image: redis
    volumes:
      - ./data:/data
    ports:
      - 6397:6379

