# Generated by Django 3.2 on 2021-09-08 04:48

from django.db import migrations, models
import poco_common


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_by_user_id', models.PositiveIntegerField(blank=True, null=True)),
                ('updated_by_user_id', models.PositiveIntegerField(blank=True, null=True)),
                ('slug', models.CharField(db_index=True, default=poco_common.core.models.make_slug, max_length=32)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, validators=[
                    poco_common.core.utils.validators.email, poco_common.core.utils.validators.lower_case])),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.TextField(blank=True, choices=[('ACTIVE', 'ACTIVE'), ('APPLIED', 'APPLIED'), ('APPROVED', 'APPROVED'), ('CANCELED', 'CANCELED'), ('CREATED', 'CREATED'), ('DEFAULT', 'DEFAULT'), ('INACTIVE', 'INACTIVE'), ('REJECTED', 'REJECTED'), ('SUSPENDED', 'SUSPENDED'), ('UNQUALIFIED', 'UNQUALIFIED')], default='CREATED', null=True)),
                ('is_test', models.BooleanField(db_index=True, default=False)),
                ('client_tier', models.TextField(blank=True, choices=[('enterprise', 'enterprise'), ('smb', 'smb'), ('standard', 'standard')], default='standard', null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
