# Generated by Django 3.2 on 2021-09-12 12:42

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import poco_common


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SymbolInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(db_index=True, default=poco_common.core.models.make_slug, max_length=32)),
                ('symbol', models.CharField(db_index=True, max_length=20, unique=True)),
                ('status', models.CharField(max_length=30)),
                ('baseAsset', models.CharField(max_length=10)),
                ('quoteAsset', models.CharField(max_length=10)),
                ('baseAssetPrecision', models.IntegerField()),
                ('quotePrecision', models.IntegerField()),
                ('quoteAssetPrecision', models.IntegerField()),
                ('baseCommissionPrecision', models.IntegerField()),
                ('quoteCommissionPrecision', models.IntegerField()),
                ('orderTypes', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, null=True), blank=True, default=list, size=None)),
                ('icebergAllowed', models.BooleanField()),
                ('ocoAllowed', models.BooleanField()),
                ('quoteOrderQtyMarketAllowed', models.BooleanField()),
                ('isSpotTradingAllowed', models.BooleanField()),
                ('isMarginTradingAllowed', models.BooleanField()),
                ('permissions', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, null=True), blank=True, default=list, size=None)),
                ('exchange_name', models.CharField(default='Binance', max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('filters', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(blank=True, default=dict, null=True), blank=True, default=list, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='LooperSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(default=poco_common.core.models.make_slug, max_length=32)),
                ('is_running', models.BooleanField(blank=True, default=None, null=True)),
                ('grabber_run_slug', models.CharField(blank=True, default=None, max_length=32, null=True)),
                ('run_type', models.TextField(blank=True, choices=[('UPDATE_SYMBOLS_ONLY', 'UPDATE_SYMBOLS_ONLY'), ('UPDATE_BALANCES_ONLY', 'UPDATE_BALANCES_ONLY'), ('UPDATE_PAIRS_ONLY', 'UPDATE_PAIRS_ONLY'), ('UPDATE_SYMBOLS_AND_BALANCES_AND_PAIRS', 'UPDATE_SYMBOLS_AND_BALANCES_AND_PAIRS'), ('UPDATE_SYMBOLS_AND_BALANCES', 'UPDATE_SYMBOLS_AND_BALANCES'), ('UPDATE_BALANCES_AND_PAIRS', 'UPDATE_BALANCES_AND_PAIRS'), ('UPDATE_SYMBOLS_AND_PAIRS', 'UPDATE_SYMBOLS_AND_PAIRS')], default=None, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='looper_settings_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GrabberRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(db_index=True, default=poco_common.core.models.make_slug, max_length=32)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.TextField(blank=True, choices=[('ACTIVE', 'ACTIVE'), ('CANCELED', 'CANCELED'), ('CREATED', 'CREATED'), ('INACTIVE', 'INACTIVE'), ('REJECTED', 'REJECTED'), ('SUSPENDED', 'SUSPENDED')], default='CREATED', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='grabber_runs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
