# Generated by Django 3.2 on 2021-09-18 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_binanceaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binanceaccount',
            name='updateTime',
            field=models.BigIntegerField(),
        ),
    ]
