# Generated by Django 3.2 on 2021-11-19 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20211118_2028'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GrabberRun',
        ),
    ]
