# Generated by Django 3.2 on 2021-11-19 13:40

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import poco_common.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_delete_grabberrun'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrabberSettingsRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(default=poco_common.core.models.make_slug, max_length=32)),
                ('is_running', models.BooleanField(default=False)),
                ('symbols', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, null=True), blank=True, default=list, size=None)),
                ('account_keys', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, null=True), blank=True, default=list, size=None)),
                ('state', models.TextField(blank=True, choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE'), ('SUSPENDED', 'SUSPENDED')], default=None, null=True)),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
                ('created_record', models.DateTimeField(auto_now_add=True)),
                ('inserted_by_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='grabber_settings_record_inserted_user', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='grabber_settings_record_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
