# Generated by Django 3.2 on 2021-11-19 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20211119_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='grabbersettingsrecords',
            name='is_record_created',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
