# Generated by Django 3.2 on 2021-11-19 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_grabbersettingsrecords_is_record_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grabbersettingsrecords',
            name='inserted_by_user',
        ),
    ]
