# Generated by Django 3.2 on 2021-11-19 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_grabbersettingsrecords_inserted_by_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.TextField(blank=True, choices=[('GRABBER', 'GRABBER'), ('TRADER', 'TRADER'), ('GRABBER_AND_TRADER', 'GRABBER_AND_TRADER')], default=None, null=True),
        ),
    ]
