# Generated by Django 3.2 on 2021-11-21 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import poco_common.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_user_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SymbolEarliestTimestamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(db_index=True, default=poco_common.core.models.make_slug, max_length=32)),
                ('symbol', models.CharField(db_index=True, max_length=20, unique=True)),
                ('earliest_timestamp', models.BigIntegerField(blank=True, default=None, null=True)),
                ('earliest_datetime', models.DateTimeField(blank=True, default=None, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='symbol_earliest_timestamp_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
