# Generated by Django 3.2 on 2021-11-21 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_symbolearliesttimestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbolearliesttimestamp',
            name='interval',
            field=models.CharField(blank=True, db_index=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='symbolearliesttimestamp',
            name='symbol',
            field=models.CharField(db_index=True, max_length=20),
        ),
    ]
