# Generated by Django 3.2 on 2021-11-21 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import poco_common.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_symbolearliesttimestamp_interval'),
    ]

    operations = [
        migrations.CreateModel(
            name='BinanceAccountStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(db_index=True, default=poco_common.core.models.make_slug, max_length=32)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.TextField(blank=True, default=None, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='binance_account_status_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
