# Generated by Django 3.2 on 2021-11-22 15:42

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import poco_common.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_binanceaccountstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(db_index=True, default=poco_common.core.models.make_slug, max_length=32)),
                ('coin', models.CharField(db_index=True, max_length=10, unique=True)),
                ('depositAllEnable', models.BooleanField()),
                ('withdrawAllEnable', models.BooleanField()),
                ('name', models.TextField(blank=True, null=True)),
                ('free', models.FloatField()),
                ('locked', models.FloatField()),
                ('freeze', models.FloatField()),
                ('withdrawing', models.FloatField()),
                ('ipoing', models.FloatField()),
                ('ipoable', models.FloatField()),
                ('storage', models.FloatField()),
                ('isLegalMoney', models.BooleanField()),
                ('trading', models.BooleanField()),
                ('networkList', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(blank=True, default=dict, null=True), blank=True, default=list, size=None)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='coin_info_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
