# Generated by Django 3.2 on 2021-09-18 09:22

import core.models
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_grabberrun_loopersettings_symbolinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='BinanceAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(db_index=True, default=core.models.make_slug, max_length=32)),
                ('makerCommission', models.IntegerField()),
                ('takerCommission', models.IntegerField()),
                ('buyerCommission', models.IntegerField()),
                ('sellerCommission', models.IntegerField()),
                ('canTrade', models.BooleanField()),
                ('canWithdraw', models.BooleanField()),
                ('canDeposit', models.BooleanField()),
                ('updateTime', models.IntegerField()),
                ('accountType', models.CharField(max_length=60)),
                ('balances', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(blank=True, default=dict, null=True), blank=True, default=list, size=None)),
                ('permissions', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, null=True), blank=True, default=list, size=None)),
                ('url', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='binance_account_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
